config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :categories
  resources :products do 
    resources :reports
    end 
  root 'welcome#index'
  get 'welcome/index'
  get 'products/index'
  get 'categories/new'
  get 'orders/myorder'
  resources :charges
  resources :contactadmins
  get 'contactadmins/new'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
    mount_uploader :image, ImageUploader
end

app/models/complain.rb
class Complain < ApplicationRecord
end

app/models/contactadmin.rb
class Contactadmin < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :reports
	
	def self.search(term)
	  if term
	    where('name LIKE ?', "%#{term}%").order('id DESC')
	  else
	    order('id DESC') 
	  end
	end
	
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/complains_controller.rb
class ComplainsController < ApplicationController
	def show
		@complain = Complain.find(params[:id])
	end  

  def create
	  @complain = complain.new(complain_params)
	 
	  @complain.save
	  redirect_to @complain
	end
 
	private
	  def complain_params
	    params.require(:complain).permit(:name, :title, :text)
	  end
end

app/controllers/contactadmins_controller.rb
class ContactadminsController < ApplicationController
	def index
    @contactadmins = Contactadmin.all
  end
 
  def show
    @contactadmin = Contactadmin.find(params[:id])
  end
 
  def new
    @contactadmin = Contactadmin.new
  end
 
  def edit
    @contactadmin = Contactadmin.find(params[:id])
  end
 
  def create
    @contactadmin = Contactadmin.new(contactadmin_params)
 
    if @contactadmin.save
      redirect_to @contactadmin
    else
      render 'new'
    end
  end
 
  def update
    @contactadmin = Contactadmin.find(params[:id])
 
    if @contactadmin.update(contactadmin_params)
      redirect_to @contactadmin
    else
      render 'edit'
    end
  end
 
  def destroy
    @contactadmin = Contactadmin.find(params[:id])
    @contactadmin.destroy
 
    redirect_to contactadmins_path
  end
 
  private
    def contactadmin_params
      params.require(:contactadmin).permit(:name, :title, :text)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def myorder
		OrderMailer.order_created(current_user).deliver_now
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order("created_at DESC")
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
  end
  

  # GET /products/new
  def new 
    @product = Product.new 
    @categories = Category.all.map{|c| [ c.name, c.id ] }
end
  # GET /products/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id] 
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :category_id,:image)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	
	 def create
    @product = Product.find(params[:product_id])
    @report = @product.reports.create(report_params)
    redirect_to product_path(@product)
  end
 
  private
    def report_params
      params.require(:report).permit(:Name, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/complain_helper.rb
module ComplainHelper
end

app/helpers/contactadmins_helper.rb
module ContactadminsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/contactadmins/_form.html.erb
<table border="2px" align="center" width="30%", style="background-color:violet "><td><%= form_with model: @contactadmin, local: true do |form| %>
 
  <% if @contactadmin.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contactadmin.errors.count, "error") %> prohibited
        this contactadmin from being saved:
      </h2>
      <ul>
        <% @contactadmin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
</td>
</table>

app/views/contactadmins/edit.html.erb
<center>
<h1>Edit Complain</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', contactadmins_path %>
</center>

app/views/contactadmins/index.html.erb
<table border="2px" align="center" width="50%", style="background-color:violet ">
<center><h1>All Complains</h1></center>
<td>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @contactadmins.each do |contactadmin| %>
    <tr>
      <td><%= contactadmin.name %></td>
      <td><%= contactadmin.title %></td>
      <td><%= contactadmin.text %></td>
      <td><%= link_to 'Show', contactadmin_path(contactadmin),class:"btn btn-success" %></td>
      
      <td><%= link_to 'Destroy', contactadmin_path(contactadmin),
              method: :delete,
              data: { confirm: 'Are you sure?' } ,class:"btn btn-success"%></td>
    </tr>
  <% end %>
</td>
</table>

app/views/contactadmins/new.html.erb
<center>
<h1>New Complain</h1>
 
<%= render 'form' %>
</center>

app/views/contactadmins/show.html.erb
<table border="2px" align="center" width="30%", style="background-color:violet "><td>
<p>
  <strong>Name:</strong>
  <%= @contactadmin.name %>
</p>
<p>
  <strong>Title:</strong>
  <%= @contactadmin.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @contactadmin.text %>
</p>
<%if current_user && current_user.admin %>
<%= link_to 'Back', contactadmins_path,class:"btn btn-success" %>
<%end%>
</td>
</table>