config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :categories
  resources :products do 
    resources :reports
    end 
  root 'welcome#index'
  get 'welcome/index'
  get 'products/index'
  get 'categories/new'
  get 'orders/myorder'
  resources :charges
  resources :contactadmins
  get 'contactadmins/new'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
    mount_uploader :image, ImageUploader
end

app/models/complain.rb
class Complain < ApplicationRecord
end

app/models/contactadmin.rb
class Contactadmin < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :category
	has_many :reports
	
	def self.search(term)
	  if term
	    where('name LIKE ?', "%#{term}%").order('id DESC')
	  else
	    order('id DESC') 
	  end
	end
	
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
     
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc, :image)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/complains_controller.rb
class ComplainsController < ApplicationController
	def show
		@complain = Complain.find(params[:id])
	end  

  def create
	  @complain = complain.new(complain_params)
	 
	  @complain.save
	  redirect_to @complain
	end
 
	private
	  def complain_params
	    params.require(:complain).permit(:name, :title, :text)
	  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def myorder
		OrderMailer.order_created(current_user).deliver_now
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order("created_at DESC")
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
  end
  

  # GET /products/new
  def new 
    @product = Product.new 
    @categories = Category.all.map{|c| [ c.name, c.id ] }
end
  # GET /products/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category_id = params[:category_id] 
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category_id = params[:category_id]
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :category_id,:image)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	
	 def create
    @product = Product.find(params[:product_id])
    @report = @product.reports.create(report_params)
    redirect_to product_path(@product)
  end
 
  private
    def report_params
      params.require(:report).permit(:Name, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/complain_helper.rb
module ComplainHelper
end

app/helpers/contactadmins_helper.rb
module ContactadminsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_form.html.erb
<table border="2px" align="center" width="20%", style="background-color: violet ">
  <td><%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div><br>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div><br>

  <div class="field">
    <%= form.label :image%>
    <%= form.file_field :image %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div><br>

<% end %>
</td></table>

app/views/categories/edit.html.erb
<center><h1 style="color:green">Category</h1>
<br>
<%= render 'form', category: @category %>
<br>
<%= link_to 'Show', @category, class:"btn btn-success" %> 
<%= link_to 'Back', categories_path,class:"btn btn-success"  %>
</center>

app/views/categories/index.html.erb
<table border="2px" align="center" width="30%", style="background-color:violet "><td><p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= image_tag category.image_url.to_s, style:"height: 70px; width: 100px;" %></td>
        <td><%= link_to 'Show', category,class:"btn btn-success"%></td>
        
        <td><%= link_to 'Edit', edit_category_path(category),class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger"%></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', products_path, class:"btn btn-success" %>
<%= link_to 'New Category', new_category_path, class:"btn btn-success" %>
</td>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path,class:"btn btn-success"%>

app/views/categories/show.html.erb
<br><table border="2px" align="center" width="25%", style="background-color: violet ">
  <td><p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>
<p><%= image_tag @category.image_url.to_s, style:"height: 70px; width: 100px;" %></p>
<%if current_user && current_user.admin %>
<%= link_to 'Edit', edit_category_path(@category),class:"btn btn-success"%> |
<%end%>
<%= link_to 'Back', products_path,class:"btn btn-success" %>
<h3 style="color:green"> Products under this category </h3>
<% Product.where(category_id: @category.id).each do |product| %>
<li> <%= link_to product.name, product ,class:"btn btn-success"%> </li><br>
<% end %>
</td></table>

app/views/products/_form.html.erb
<center><table border="2px" align="center" width="20%", style="background-color: violet ">
  <td>
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>
   <br>
  <div class="field">
    <%= form.label :price%>
    <%= form.text_field :price %>
  </div>
  <br>
   <div class="field">
    <%= form.label :image%>
    <%= form.file_field :image %>
  </div>
  <br>
  <div >Category:
    <%= select_tag(:category_id, options_for_select(@categories), :include_blank => "Select One") %>
  </div><br>

  <div class="actions">
    <%= form.submit %><br>
  </div>
<% end %>
</td>
</table>
</center>

app/views/products/edit.html.erb
<center><h1 style="color:green">Editing Product</h1>
<br>
<%= render 'form', product: @product %>
<br>
<%= link_to 'Show', @product,class:"btn btn-success" %> 
<%= link_to 'Back', products_path, class:"btn btn-success" %>
</center>

app/views/products/index.html.erb
<div class="header">
  <a class="logo">Online Shopping....</a>
  <div class="header-right">
      <%= link_to "All Products", products_path, class:"btn btn-success" %>
      
      <%= link_to "Add a Complain", contactadmins_new_path, class:"btn btn-success" %>
       <%if current_user && current_user.admin %>
       <%= link_to "Show Complain", contactadmins_path, class:"btn btn-success" %> <%end%>
      <a href=""></a>
      <a href=""></a>
      <a href=""></a>

    </div>
</div> <br>
<%if current_user && current_user.admin %>
<center><%= link_to 'Add new Product', new_product_path, class:"btn btn-success" %>
<%= link_to 'All Category', categories_path, class:"btn btn-success"%>
</center>
<%end%>

 <%= form_tag(products_path, :method => "get", id: "search-form") do %>
   <%= text_field_tag :search, params[:search],placeholder: "Search products"%>
   <%= submit_tag 'Search', :name => nil, class:"btn btn-success"%>
   

<% end %>


<p id="notice"><%= notice %></p>

<h1 align="center" style="color:magenta">All Products</h1><br>

<table border="2px" width="100%" >
  <td>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price in Rs.</th>
      <th>Image</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    

  <% @products.each do |product| %>
      <tr>
        <td><h3 style="color:green"><%= product.name %></h3></td>
        <td><h3 style="color:green"><%= product.price %></h3></td>
        <td><%= image_tag product.image_url.to_s, style:"height: 70px; width: 100px;" %></td>
        <td><%= link_to Category.find(product.category_id).name, category_path(product.category_id), class:"btn btn-primary btn-md" %></td>
        <td><%= link_to 'Show', product, class:"btn btn-success"%></td>
       
        
        <%if current_user && current_user.admin %>
      
        <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-success" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-success" %></td>
          <% end %>
      </tr>
    <% end %>
    
  </tbody>
  </td>
</table>

<br>

app/views/products/new.html.erb
<center><h1 style="color:green">New Product</h1>
<br>
<%= render 'form', product: @product %>
<br>
<%= link_to 'Back', products_path, class:"btn btn-success"%>
</center>

app/views/products/show.html.erb
<table border="2px" align="center" width="20%", style="background-color: violet ">
  <td>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.try(:name)%>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.try(:price)%>
</p>
<p><%= image_tag @product.try(:image_url).to_s, style:"height: 70px; width: 100px;" %></p>
<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>
</td></table><br>
<center><td><%= link_to 'Order', orders_myorder_path,  class:"btn btn-success"  %></td>
<%= link_to "Payment" , new_charge_path,  class:"btn btn-success"  %>

<%= link_to 'Back', products_path,  class:"btn btn-success"  %>

<%if current_user && current_user.admin %>
 

<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-success" %> |
<%end%><br><br>
<table border="2px" align="center" width="20%", style="background-color: lime ">
  <td>
<h2>Comments</h2>
<% @product.reports.each do |report| %>
  <p>
    <strong>Name:</strong>
    <%= report.Name %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= report.body %>
  </p>
<% end %></td></table>
 <table border="2px" align="center" width="20%", style="background-color: yellow ">
  <td>
<h2>Comments on product:</h2>
<%= form_with(model: [ @product, @product.reports.build ], local: true) do |form| %>
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :Name %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
</td></table>
<%= link_to 'Back', products_path, class:"btn btn-success" %>
</center>